name: url-alias-service-api

services:
  app:
    image: python:3.11-slim
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "80:8000"
    depends_on:
      - db
    command: bash -c './start.sh'
    restart: unless-stopped

  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
